# Generated by Django 5.2 on 2025-04-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestchambre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('type_chambre', models.CharField(choices=[('simple', 'Simple'), ('double', 'Double'), ('suite', 'Suite')], max_length=10)),
                ('prix_par_nuit', models.DecimalField(decimal_places=2, max_digits=7)),
                ('etat', models.CharField(choices=[('libre', 'Libre'), ('réservée', 'Réservée'), ('occupée', 'Occupée')], default='libre', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('nombre_de_lits', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='chambres/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
